//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioQEncode {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class EncoderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EncoderSettings defaultInstance = ((EncoderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EncoderSettings())));
        
        public static EncoderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte MP3Bitrate {
            get {
                return ((byte)(this["MP3Bitrate"]));
            }
            set {
                this["MP3Bitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte MP3Quality {
            get {
                return ((byte)(this["MP3Quality"]));
            }
            set {
                this["MP3Quality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string lamePath {
            get {
                return ((string)(this["lamePath"]));
            }
            set {
                this["lamePath"] = value;
            }
        }
    }
}
